---
title: "Final Grade Reflection"
author: "Camille Heathcock"
format: pdf
editor: visual
---

In this document, you make a data-based argument for the grade you've earned in this course. Your argument should include evidence from the supporting artifacts you've provided.

## The output document should be a PDF or a Word Document, as it should be a **maximum** of 2-pages.

**How have you demonstrated a commitment to continued learning?**

I have demonstrated a commitment to continued learning through my dedication to understand my past mistakes. I spend a fair amount of time completing the initial assignments for this class, but oftentimes I am not able to perfect them the first time around. However, I think there is so much value in receiving feedback from a coding expert (Dr. T), and developing my initial attempt at a solution. I really appreciate that I am able to build on my initial encoding of the class curriculum by going back to my past work and revising my thinking. This allows my brain to reinforce the concepts we have learned, as well as encourages me to tie different concepts from different weeks together within my code. Additionally, I am able to reinforce class concepts within the structure of class and office hours. Oftentimes, I will learn a concept but not fully understand it until I see how it is used in context. The in-person meetings allow me to develop my thinking and really let the concepts click. I appreciate that we have many opportunities to learn and relearn the theories that are relevant for the course, and apply them in various contexts. All in all, I have demonstrated a commitment to continued learning through my class participation and revision process.

**How have you grown as a team member and leader?**

I have grown as a team member through my communication and collaboration skills. I often get stuck on a tiny part of a given assignment-- whether it be a syntax error or otherwise, it is very frustrating. I have developed various troubleshooting techniques for when I encounter this kind of issue, like using the help file and stack overflow, as well as checking the discord channel. However, it is nice to have a team as a support system for small issues like this. It is always good to have a fresh eye look at something I have been grueling over, as I am often missing an obvious flaw in the code. I have become much more comfortable communicating with my team about various assignments and issues. Additionally, I am always happy to help out my team members if they are confused about something that I understand. In terms of the ways I have grown within my team, I think I have developed as a team member and leader. I always try to make sure the members of our team are on the same page, and facilitate a group conversation if it needs to be had.

**How have you contributed to creating a respectful classroom learning community?**

I have contributed to creating a respectful classroom learning community through my participation and engagement during class. I really appreciate the dynamic of the STAT 331 classroom, because I feel very comfortable asking questions, as well as collaborating with the people around me. It is a very inclusive and low-stakes environment, so I feel quite comfortable participating in class discussions. I also appreciate that the whole class works on the same assignment at once, because I will often listen in on questions my fellow classmates have asked, which can be extremely helpful.

**Are you accomplishing the goals you outlined for yourself at the start of the course?**

The goals I outlined at the start of the course were: To thoroughly understand what is expected from me and keep up with the workload, and to be able to write R code that is not only useful for all sorts of applications, but also allows me to express creativity. Unfortunately, I don't think I have fully achieved the first goal. I feel as though I understand what is expected of me and I understand the flow and workload of the class. However, I have not been the best at keeping up with all of our assignments. Around week 4-5, I got quite behind on the coursework. This was quite frustrating when attempting activities in class, as I felt very behind and lost. However, I am proud of myself for rebounding from this self-imposed setback and catching up the following weekend. Instead of wallowing in my stressed state of being, I dedicated time to learning the concepts that I had not grasped. My goal for the rest of the quarter is to keep up with the outlined concepts and stay on top of the workload. My second goal outlined at the start of the course was to creatively write R code that is useful in all sorts of applications. As I said in my last reflection, this goal is a broad one. I can't say I have fully achieved this, as I think I have a lot of room for improvement as a programmer. However, I think I am working in the right direction. Even since I wrote the last reflection, I feel as though I have developed my coding skills a lot and am able to do many more of the learning targets. My new developed goal for the last few weeks of the quarter is to get better at being creative within the context of a particular assignment, especially when given creative freedom. I struggled on this in Challenge 4, when we were tasked with creating a useful application of a dataset that we found. I hope to improve my skills in this area by my final reflection. To conclude, although I have not fully achieved the goals I outlined for myself, I feel confident in my ability to achieve them by the end of the quarter. I feel as though I deserve a B+ for my work in the class. I don't think I have quite crossed the threshold into the A range, especially since I was behind for a little while. However, I think I have demonstrated proficiency for many of the learning targets, and hopefully it will be a majority of the learning targets by the end of the quarter. In terms of revising my thinking, I think I have regularly learned from my revisions, which has impacted my code in subsequent assignments, and I think I have generally revised all of the assignments when the opportunity is given. I have also extended my thinking by completing most of the challenge assignments and challenging myself within the context of these problems. I hope to challenge myself even more throughout the remainder of the quarter. I also think I have been a great team member. I am good at encouraging communication within my team and will ask Dr. T. questions when necessary. I am always present and cooperative, I always fill my role in the team, and I always try to be as respectful as possible. However, since I was behind for a little while, I am more in the B range for being prepared for class each week, as well as completing assignments and quizzes on time. In terms of peer-reviewing code, I think I have been responsive to constructive criticism, and have put my best effort into reviewing my peers' code. For the code I have reviewed, I have given constructive criticism with kindness, as well as praised good qualities of other's code. However, I am more in the B range for this requirement, since I have not been able to consistently complete peer-reviews for assignments I have turned in late.
