---
title: "Practice Activity 9"
author: Camille Heathcock
execute: 
  echo: true
  error: true
format: 
  html: 
    code-fold: true
    self-contained: true
    theme: cosmo
editor: visual
---

# **Practice Activity 9.1: Regression**

## **1) Data**

```{r packages}
#| echo: False 
#| output: False
library(tidyverse)
library(dplyr)
library(glue)
library(stringr)
library(purrr)

mystery_animal <- read_csv(here::here("supporting_artifacts", "datasets", "mystery_animal.csv"))
```

## **2) Linear Regression**

```{r}
limear <- lm(weight_before ~ weight_after, data = mystery_animal)

limear <- mystery_animal %>% 
  lm(weight_before ~ weight_after, data = .)
```

## **3) Residuals**

```{r}
limear %>% 
  ggplot(mapping = aes(y = .resid, x = .fitted)) +
  geom_point()

linear_t <- broom::augment(limear)

```

# **Practice Activity 9.2: Simulation**

## **Warm-up**

```{r data-simulation}
dunif(95, min = 1.5, max = 3.5)
pnorm(10, mean = 4.6, sd = 0.8)
rnorm(100, mean = 4.6, sd = 0.8)
```

```{r}
music_man <- function(n_tromb, n_cor, n_reed){
  
  trombones <- rnorm(n_tromb, mean = 4.6, sd = 0.8)
  cornets <- runif(n_cor, min = 1.5, max = 3.5)
  reeds <- rchisq(n_reed, df = 4)
  
  return(sum(trombones, cornets, reeds))
  
}


set.seed(1957)

my_weights <- rerun(.n = 1000, 
                    music_man(n_tromb = 76, n_cor = 110, n_reed = 1035)
                    ) |> 
  flatten_dbl()

music_man(n_tromb = 76, n_cor = 110, n_reed = 1035)

length(my_weights[my_weights < 4532])
```
