---
title: "Practice Activity 4"
author: Camille Heathcock
format: 
  html:
    self-contained: true
editor: visual
---

## Loading in Data

```{r}
#| echo: False 
#| output: False
library(readxl) 
library(tidyverse)
```

```{r}
military <- read_xlsx(here::here("datasets", 
                                 "gov_spending_per_capita.xlsx"), 
                      sheet = "Share of Govt. spending", 
                      skip = 6, 
                      n_max = 190)
```

### Data Cleaning

```{r}
military_clean <- military |>  
  mutate(across(.cols = everything(), ~na_if(., "xxx")), 
         across(.cols = everything(), ~na_if(., ". .")))
```

```{r}
military_clean <- military_clean |> 
  mutate(across(.cols = "1988" : "2019", ~as.numeric(.)))
```

```{r}
cont_region <- read_xlsx(here::here("datasets",
                                    "gov_spending_per_capita.xlsx"), 
                      sheet = "Regional totals", 
                      skip = 14) |> 
  filter(Region != "World total (including Iraq)", 
         Region != "World total (excluding Iraq)")
```

```{r}
military_clean <- military_clean |> 
  anti_join(cont_region, by = c("Country" = "Region"))
```
